name: flutter-build

on:
  push:
    branches:
      - main
jobs:
    build-android:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-java@v1
              with:
                  distribution: 'adopt'
                  java-version: '11'
            - name: Set up Flutter
              uses: subosito/flutter-action@v2
              with:
                  channel: stable
                  flutter-version: '3.22.3'
            - name: Install dependencies
              run: flutter pub get
            - name: Build APK
              run: flutter build apk --release
            - name: Rename APK
              run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/squarecloud.apk
            - name: Archive production artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: squarecloud.apk
                  path: build/app/outputs/flutter-apk/squarecloud.apk
    build-ios:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Flutter
              uses: subosito/flutter-action@v2
              with:
                  flutter-version: '3.22.3'
            - name: Install dependencies
              run: flutter pub get
            - name: Build iOS
              run: flutter build ios --release --no-codesign
            - name: Make Result Folder
              run: mkdir build/ios/iphoneos/Result
            - name: Make Payload Folder
              run: mkdir build/ios/iphoneos/Result/Payload
            - name: Copy .app to Payload folder
              run: mv build/ios/iphoneos/Runner.app build/ios/iphoneos/Result/Payload/Runner.app
            - name: Install Zip Lib
              uses: montudor/action-zip@v1
            - name: Zip .app to .ipa
              run: zip -qq -r squarecloud.ipa Result/
              working-directory: build/ios/iphoneos
            - name: Archive production artifacts
              uses: actions/upload-artifact@v2
              with:
                    name: squarecloud.ipa
                    path: build/ios/iphoneos/squarecloud.ipa